version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      # - pip install -r requirements.txt -t lib
      - touch readme.md
      - mkdir lib
      - mv readme.md lib/readme.md
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package_lf_search.zip .
      - zip -r9 ../deployment_package_lf_index.zip .
      - cd ..
      - mv search_photos.py lambda_function.py
      - zip -g deployment_package_lf_search.zip lambda_function.py
      - mv lambda_function.py search_photos.py
      - mv index_photos.py lambda_function.py
      - zip -g deployment_package_lf_index.zip lambda_function.py
      - mv lambda_function.py index_photos.py
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name search-photos --zip-file fileb://deployment_package_lf_search.zip
      - aws lambda update-function-code --function-name index-photos --zip-file fileb://deployment_package_lf_index.zip
      - echo "DONE!!"